language: java

# We need Ubuntu 14.04 due to very new JUnit API which WoT needs
dist: trusty
# Disabling sudo routes the build to a Docker container instead of a VM
# which speeds up the build.
sudo: false

env:
  - FREENET_MINIMUM_JAVA_VERSION=7

addons:
  apt:
    packages:
    - ant
    - ant-optional
    - junit4
    - libhamcrest-java
    # For .travis.upload-jar-to-freenet.sh
    - python3-pip
  # TODO: Code quality: Remove this workaround for https://github.com/travis-ci/travis-ci/issues/5227
  hosts:
    - freenet-plugin-WebOfTrust
  hostname: freenet-plugin-WebOfTrust

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f  $HOME/.gradle/caches/jars-2/jars-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  apt: true
  directories:
  - $TRAVIS_BUILD_DIR/../fred/
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

# Get/update Freenet Git repository
install:
  - cd "$TRAVIS_BUILD_DIR"/..
  - |
    if [ ! -e fred/.git ] ; then # Must check subdir, main one will be created by Travis cache config.
      FRED_UPDATED=1
      git clone https://github.com/freenet/fred.git --branch next --single-branch --depth 1 fred
    fi
  - cd fred
  - git reset --hard # Undo our manual changes to ./gradlew to prevent merge conflicts
  - git fetch && if [ "$(git rev-parse @)" != "$(git rev-parse @{u})" ] ; then FRED_UPDATED=1 ; git pull ; fi
  - cd "$TRAVIS_BUILD_DIR"

# Compile Freenet Git repository, start a node
before_script: |
  if [ "$FRED_UPDATED" = 1 ] ; then
    cd "$TRAVIS_BUILD_DIR"/../fred &&
    # The gradlew binary which fred ships doesn't work on OpenJDK 7, need to use Travis' gradle there.
    if [ "$TRAVIS_JDK_VERSION" = "openjdk7" ] ; then
      rm ./gradlew &&
      ln -s "$(which gradle)" ./gradlew
    fi &&
    if [[ "$TRAVIS_JDK_VERSION" = "openjdk9" || "$TRAVIS_JDK_VERSION" = "openjdk10" ]] ; then
      # Workaround for Gradle failing on openjdk9 and above with:
      #   sun.security.validator.ValidatorException: PKIX path building failed: [...]
      # TODO: Code quality: Added 2018-09-26, remove after some time and see if it works without this.
      USE_SYSTEM_CERTS=1 &&
      mv "${JAVA_HOME}/lib/security/cacerts" "${JAVA_HOME}/lib/security/cacerts.jdk" &&
      ln -s '/etc/ssl/certs/java/cacerts' "${JAVA_HOME}/lib/security/cacerts"
    fi &&
    # TODO: freenet.jar won't contain class Version if we don't run the
    # clean task in a separate execution of Gradle. I.e. this wouldn't work:
    #   $ gradle clean jar
    # This is due to a bug in fred's Gradle script which could be fixed
    # like this WoT commit did: 06c007204f40c712a398f0b58671f77fd9aeffd1
    ./gradlew clean &&
    # "copyRuntimeLibs" copies the JAR *and* dependencies - which WoT also
    # needs - to build/output/
    ./gradlew jar copyRuntimeLibs -x test &&
    if [ "$USE_SYSTEM_CERTS" = 1 ] ; then
        rm "${JAVA_HOME}/lib/security/cacerts" &&
        mv "${JAVA_HOME}/lib/security/cacerts.jdk" "${JAVA_HOME}/lib/security/cacerts"
    fi &&
    cd "$TRAVIS_BUILD_DIR"
  else
    echo "No changes at fred, not recompiling."
  fi
  if [ "$TRAVIS_JDK_VERSION" = "openjdk$FREENET_MINIMUM_JAVA_VERSION" ] ; then
    echo "Starting a Freenet node already to establish connectivity far before deploy stage..."
    "$TRAVIS_BUILD_DIR"/.travis.start-freenet.sh
  fi

# Compile and test WoT
script:
  - set -o errexit
  - echo 'Checksums of dependencies:' ; sha256sum ../fred/build/output/*
  # Don't allow Travis to override the low memory limit which our builder sets with a higher one.
  - unset _JAVA_OPTIONS
  # Use Gradle instead of Ant as it supports using multiple CPU cores on the unit tests.
  # Use the same Gradle as fred to re-use the fixes we applied to it above and because Travis'
  # Gradle version is too old for Java >= 9.
  - ln -sf "$TRAVIS_BUILD_DIR/../fred/gradlew"
  - ./gradlew clean test jar
  # To test the Ant and Gradle builders against each other uncomment the following.
  ## - tools/compare-gradle-jars-with-ant-jars
  ## - tools/compare-gradle-tests-with-ant-tests

jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  # oraclejdk10: Not supported anymore: https://changelog.travis-ci.com/stop-a-job-early-if-a-deprecated-jdk-is-configured-76612
  # oraclejdk7: Not supported anymore: https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879

deploy:
  provider: script
  # Prevent Travis from deleting the JAR before we can deploy it (wtf?)
  skip_cleanup: true
  script: ./.travis.upload-jar-to-freenet.sh
  on:
    all_branches: true
    condition: $TRAVIS_JDK_VERSION = "openjdk$FREENET_MINIMUM_JAVA_VERSION"
